services:
  blast-radius-api:
    image: blast-radius-api:latest
    container_name: blast-radius-api
    build:
      context: ./blast-radius-api
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - blast-radius

networks:
  blast-radius:
    driver: bridge
