spring:
  application:
    name: blast-radius-api

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      service: ${spring.application.name}
      environment: local
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
  endpoint:
    health:
      show-details: never
